### ISSUE TITLE
Update status on test-run element

### ISSUE THREAD

**Issue by StijnBt** [tfenster/automated-al-testing#1]
Hello,

There's no attribute status on the "run" element, possible it's "result" that should be referred here?

https://github.com/tfenster/automated-al-testing/blob/02dba52657c02a6b54af5055f21fcbe6d2d1151a/test%20code/BaseLibrary.al#L238

Best regards,

Stijn

**Comment by tfenster** [comment]
Hello @StijnBt,

thanks a lot for your feedback. As far as I see [here](http://nunit.org/files/testresult_30.txt) there is "status" attribute on "test-run". Am I missing sometihing?

**Comment by StijnBt** [comment]
Euhm, actually there isn't:

`<test-run id="2" name="mock-assembly.dll" fullname="D:\Dev\NUnit\nunit-3.0\work\bin\vs2008\Debug\mock-assembly.dll" testcasecount="25" result="Failed" time="0.154" total="18" passed="12" failed="2" inconclusive="1" skipped="3" asserts="2" run-date="2011-07-26" start-time="11:34:27">`

**Comment by tfenster** [comment]
@StijnBt whatever I saw last time, it clearly isn't there :( Sorry and thanks for your feedback!
